#!/bin/bash

# OS specific stuff
case $(uname) in
    Darwin)
        BASH_CONFIG=".profile"
        INSTALL_DIR="/Users/${USER}"
    ;;
    *)
        BASH_CONFIG=".bashrc"
        INSTALL_DIR="${HOME}"
esac

GIT_URL="https://github.com/tiwilliam/dotfiles.git"
STORAGE_DIR="${INSTALL_DIR}/.dotfiles"

function link_file {
    if [ -f "$2" ] || [ -d "$2" ]; then
        echo "File already exists: $2"
    else
        ln -s "$1" "$2"
    fi
}

function download_dotfiles {
    # Get latest files
    if [ -d "${STORAGE_DIR}" ]; then
        pushd ${STORAGE_DIR}
            git pull
            git submodule init
            git submodule update
        popd
    else
        git clone ${GIT_URL} ${STORAGE_DIR}
        pushd ${STORAGE_DIR}
            git submodule init
            git submodule update
        popd
    fi
}

function install_gitconfig {
    if [ ! -f "${INSTALL_DIR}/.gitconfig" ]; then
        echo 'What is your git name?'
        read -e git_name
        echo 'What is your git email?'
        read -e git_email
        sed -e "s/NAME/$git_name/g" -e "s/EMAIL/$git_email/g" ${STORAGE_DIR}/gitconfig > ${INSTALL_DIR}/.gitconfig
    fi
}

function install_dotfiles {
    for file in $(find ${STORAGE_DIR} -name "*.symlink" -maxdepth 1); do
        basename=$(basename "${file%.*}")
        destination="${INSTALL_DIR}/.${basename}"
        link_file "${file}" "${destination}"
    done

    link_file "${STORAGE_DIR}/bashrc" "${INSTALL_DIR}/${BASH_CONFIG}"
}

download_dotfiles
install_gitconfig
install_dotfiles
