#!/bin/bash

# OS specific stuff
case $(uname) in
    Darwin)
        BASH_CONFIG=".profile"
        INSTALL_DIR="/Users/${USER}"
    ;;
    *)
        BASH_CONFIG=".bashrc"
        INSTALL_DIR="${HOME}"
esac

GIT_URL="https://github.com/tiwilliam/dotfiles.git"
STORAGE_DIR="${INSTALL_DIR}/.dotfiles"

function link_file {
    link=true

    if [ -f "$2" ] || [ -d "$2" ]; then
        read -p "$2: File or directory already exists - overwrite? [y/N]"
        if [ "${REPLY}" == "y" ]; then
            rm -rf "$2"
        else
            link=false
        fi
    fi

    if [ ${link} == true ]; then
        ln -s "$1" "$2"
    fi
}

function download_dotfiles {
    # Get latest files
    if [ -d "${STORAGE_DIR}" ]; then
        pushd ${STORAGE_DIR} > /dev/null
            git pull -q
            git submodule init
            git submodule update
        popd > /dev/null
    else
        git clone ${GIT_URL} ${STORAGE_DIR} -q
        pushd ${STORAGE_DIR} > /dev/null
            git submodule init
            git submodule update
        popd > /dev/null
    fi
}

function install_gitconfig {
    if [ ! -f "${INSTALL_DIR}/.gitconfig" ]; then
        echo 'What is your git name?'
        read -e git_name
        echo 'What is your git email?'
        read -e git_email
        sed -e "s/NAME/$git_name/g" -e "s/EMAIL/$git_email/g" ${STORAGE_DIR}/gitconfig > ${INSTALL_DIR}/.gitconfig
    fi
}

function install_dotfiles {
    for file in $(find ${STORAGE_DIR} -maxdepth 1 -name "*.symlink"); do
        basename=$(basename "${file%.*}")
        destination="${INSTALL_DIR}/.${basename}"
        link_file "${file}" "${destination}"
    done

    link_file "${STORAGE_DIR}/bashrc" "${INSTALL_DIR}/${BASH_CONFIG}"
}

download_dotfiles
install_gitconfig
install_dotfiles
